FROM fedora:rawhide

RUN dnf install -y gcc make git
RUN dnf install -y golang protobuf-compiler

# build protobuf
ENV GOPATH $HOME/.go
ENV PATH=$PATH:$GOPATH/bin
RUN go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
