// Code generated by protoc-gen-go.
// source: health.proto
// DO NOT EDIT!

/*
Package health is a generated protocol buffer package.

It is generated from these files:
	health.proto

It has these top-level messages:
	PingMsg
	PongMsg
*/
package health

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMsg struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PingMsg) Reset()                    { *m = PingMsg{} }
func (m *PingMsg) String() string            { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()               {}
func (*PingMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PongMsg struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PongMsg) Reset()                    { *m = PongMsg{} }
func (m *PongMsg) String() string            { return proto.CompactTextString(m) }
func (*PongMsg) ProtoMessage()               {}
func (*PongMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*PingMsg)(nil), "health.PingMsg")
	proto.RegisterType((*PongMsg)(nil), "health.PongMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Health service

type HealthClient interface {
	Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PongMsg, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PongMsg, error) {
	out := new(PongMsg)
	err := grpc.Invoke(ctx, "/health.Health/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	Ping(context.Context, *PingMsg) (*PongMsg, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/health.Health/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Ping(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "health.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Health_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}

func init() { proto.RegisterFile("health.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x24, 0xb9, 0xd8,
	0x03, 0x32, 0xf3, 0xd2, 0x7d, 0x8b, 0xd3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x80, 0x2c, 0xb0, 0x54, 0x3e, 0x56, 0x29, 0x23, 0x13, 0x2e, 0x36, 0x0f,
	0xb0, 0x7e, 0x21, 0x2d, 0x2e, 0x16, 0x90, 0x7e, 0x21, 0x7e, 0x3d, 0xa8, 0xf1, 0x50, 0xd3, 0xa4,
	0x10, 0x02, 0x10, 0x33, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x56, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0x5f, 0x09, 0x74, 0x8a, 0x00, 0x00, 0x00,
}
